### ISSUE TITLE
Support for EF Core 7

### ISSUE THREAD

**Issue by ErikEJ** [khellang/EFCore.Sqlite.NodaTime#10]
What are the plans for EF Core 7 support?

**Comment by khellang** [comment]
I dunno. I haven't followed its development too closely beyond high level feature announcements etc. Anything I need to think about and/or update?

**Comment by ErikEJ** [comment]
I think you just need to update dependencies. I can try a PR?

**Comment by khellang** [comment]
Sure, go for it! ☺️🙏

**Comment by ErikEJ** [comment]
(I use your extension in EF Core Power Tools)

**Comment by ErikEJ** [comment]
I think an update of https://www.nuget.org/packages/Verify.EntityFramework is needed first @SimonCropp ?

**Comment by khellang** [comment]
Why exactly does EF Core require these version bumps? If a library you depend on (in this case `Verify.EntityFramework`) requires `>= 6.0.5`, shouldn't you just be able to pin `7.0.0` and everything should just work? Is it because of breaking changes?

**Comment by SimonCropp** [comment]
@ErikEJ what update do u need in Verify.EntityFramework  ?

**Comment by ErikEJ** [comment]
@SimonCropp None apparently! :smile:
