### ISSUE TITLE
Support for EF Core 8

### ISSUE THREAD

**Issue by ErikEJ** [khellang/EFCore.Sqlite.NodaTime#14]
Plan to support it? 

Happy to attempt a PR in the coming weeks

**Comment by khellang** [comment]
Hey Erik! Yeah, I just haven't had the time to get around to it yet. Any known breaking changes?

**Comment by ErikEJ** [comment]
Probably not. I will attempt a PR after RTM

**Comment by khellang** [comment]
v8.0.0 is now on NuGet

**Comment by ErikEJ** [comment]
And added to EF Core Power Tools
